from django.urls import path
from . import views

urlpatterns = [
        path('',views.homepage,name='homepage'),
        path('hospital/doctor_login/',views.doctor_login,name='doctor_login'),
        path('hospital/doctor_login/add_doctor/',views.add_doctor,name='add_doctor'),
        path('hospital/patient_login/',views.patient_login,name='patient_login'),
        path('hospital/patient_login/patient_registration/',views.patient_registration,name='patient_registration'),
        path('hospital/staff/',views.staff_view,name='staff_view'),
        path('hospital/staff/hospital/make_querry/',views.make_querry,name='make_querry'),
        path('hospital/staff/hospital/new_employee/',views.new_employee,name='new_employee'),
        path('hospital/staff/hospital/new_receptionist/',views.new_receptionist,name='new_receptionist'),
        path('hospital/staff/hospital/show_doctors/',views.show_doctors,name='show_doctors'),
        path('hospital/staff/hospital/show_patients/',views.show_patients,name='show_patients'),
        path('hospital/staff/hospital/show_employees/',views.show_employees,name='show_employees'),
        path('hospital/staff/hospital/new_drug/',views.new_drug,name='new_drug'),
        path('hospital/staff/hospital/show_medicines/',views.show_medicines,name='show_medicines'),
        path('hospital/staff/hospital/show_treatments/',views.show_treatments,name='show_treatments'),
        path('hospital/staff/hospital/show_doctors/remove/<str:Doctor_ID>/',views.doct_remove,name='doct_remove'),
        path('hospital/staff/hospital/show_employees/remove/<str:Emp_ID>/',views.emp_remove,name='emp_remove'),
        path('hospital/staff/hospital/show_patients/discharge/<str:Patient_ID>/',views.patient_discharge,name='patient_discharge'),
        path('hospital/staff/hospital/show_doctors/appointments/<str:Doctor_ID>/discharge/<str:Patient_ID>/',views.discharge,name='discharge'),
        #path('hospital/staff/hospital/show_patients/admit/<str:Patient_ID>/',views.admit,name='patient_admit'),
        path('hospital/staff/hospital/show_doctors/appointments/<str:Doctor_ID>/',views.appoint_doctor,name='appoint_doctor'),
        path('hospital/staff/hospital/show_doctors/appointments/<str:Doctor_ID>/prescription/<str:Patient_ID>/',views.prescription,name='prescription'),
        #path('hospital/staff/hospital/show_doctors/appointments/<str:Doctor_ID>/prescription/<str:Patient_ID>/save_prescription/',views.save_prescription,name='save_prescription'),
        path('hospital/staff/hospital/rooms/',views.show_rooms,name='show_rooms'),
        #path('hospital/patient_login/make_appointment/<str:Doctor_ID>/<str:Patient_ID>/',views.make_appointment,name='make_appointment'),
        path('hospital/doctor_login/appointments/<str:Doctor_ID>/',views.appoint_doctor,name='appoint_doctor'),
        path('hospital/doctor_login/appointments/<str:Doctor_ID>/prescription/<str:Patient_ID>/',views.prescription,name='prescription'),
        path('hospital/patient_login/hospital/patient_login/<str:Patient_ID>/',views.patient_dashboard,name='patient_dashboard'),
        path('hospital/patient_login/hospital/patient_login/<str:Patient_ID>/appoint/',views.appointment,name='appointment'),
        path('hospital/patient_login/hospital/patient_login/<str:Patient_ID>/show_rooms/',views.show_rooms,name='show_rooms'),
        path('hospital/patient_login/hospital/patient_login/<str:Patient_ID>/logout/',views.patient_logout,name='patient_logout'),
]
